### PR TITLE
Update favicon

### LINKED ISSUE #61: Set favicon

### PR DESCRIPTION
**Pull request by kistora**
### Description of your PR

Fix #61.

### Pre-review TODO

- [x] PR is rebased on top of `origin/master` 
- [ ] PR provide new tests for new behaviors
- [x] PR doesn't introduce commented out code
- [x] PR has been tested locally on the main use cases
- [ ] Documentation have been updated if necessary

### CODE REVIEW

**Comment by Embraser01** [comment]
Will close #61

**Comment by Embraser01** [comment]
Because we want to display the icon in multiple places with a good resolution, we should add multiple format :) You can check https://realfavicongenerator.net/ to do it quickly !

**Comment by kistora** [comment]
I've implemented a version based on K-Fêt logo. I'm not very satisfied! I will ask my girlfriend to create a simpler one.

**Comment by Embraser01** [comment]
No problem, maybe create an issue for that, I will merge this PR as soon as the CI as finished :wink:

**Pull request merged**
